<?php
/**
 * Proxy Bid Service
 *
 * @package    WooCommerce Auction
 * @subpackage Services
 * @version    1.0.0
 * @requirement REQ-AB-001: Manage proxy bid lifecycle
 * @requirement REQ-AB-008: Never exceed maximum bid
 */

namespace WC\Auction\Services;

use WC\Auction\Models\ProxyBid;
use WC\Auction\Repositories\ProxyBidRepository;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * ProxyBidService - Manages proxy bid lifecycle and business logic
 *
 * UML Class Diagram:
 * ```
 * ProxyBidService (Domain Service)
 * ├── Dependencies:
 * │   ├── ProxyBidRepository
 * │   └── Logger
 * ├── Methods:
 * │   ├── createProxyBid(user, auction, max_bid) : ProxyBid
 * │   ├── updateMaximumBid(proxy_bid, new_max) : ProxyBid
 * │   ├── cancelProxyBid(proxy_bid) : bool
 * │   ├── getActiveProxyBids(user_id) : ProxyBid[]
 * │   ├── isProxyBidActive(proxy_bid) : bool
 * │   └── endProxyBid(proxy_bid) : bool
 * └── Business Rules:
 *     ├── Never exceed maximum bid (REQ-AB-008)
 *     ├── Only one active proxy per auction+user (unique constraint)
 *     ├── Track all state transitions
 * ```
 *
 * Design Pattern: Domain Service
 * - Orchestrates proxy bid operations
 * - Enforces business rules and constraints
 * - Delegates persistence to repository
 * - Immutable domain objects (ProxyBid)
 *
 * Business Rules:
 * - Only one active proxy bid per user+auction (enforce DB uniqueness)
 * - Maximum bid never exceeded (validate before saving)
 * - Status transitions: active -> (ended|cancelled) or active -> outbid
 * - Timestamps tracked for audit trail
 *
 * @requirement REQ-AB-001: Manage proxy bid lifecycle
 * @requirement REQ-AB-008: Enforce never exceed maximum bid (thread-safe)
 * @requirement REQ-AB-009: Handle concurrent bid operations safely
 */
class ProxyBidService {
    
    /**
     * Proxy bid repository
     *
     * @var ProxyBidRepository
     */
    private $repository;
    
    /**
     * Constructor
     *
     * @param ProxyBidRepository $repository Repository instance
     */
    public function __construct( ProxyBidRepository $repository ) {
        $this->repository = $repository;
    }
    
    /**
     * Create a new proxy bid
     *
     * REQ-AB-001: Allow user to set automatic proxy bid
     * REQ-AB-008: Enforce maximum bid constraint
     *
     * @param int   $auction_id  Auction (product) ID
     * @param int   $user_id     User ID
     * @param float $maximum_bid Maximum bid amount
     * @param array $extra_data  Additional data (notes, etc.)
     * @return ProxyBid
     * @throws \Exception If creation fails
     */
    public function createProxyBid( 
        int $auction_id, 
        int $user_id, 
        float $maximum_bid, 
        array $extra_data = [] 
    ): ProxyBid {
        // Validate inputs
        if ( $maximum_bid <= 0 ) {
            throw new \InvalidArgumentException( 'Maximum bid must be greater than zero' );
        }
        
        // Check for existing active proxy bid
        $existing = $this->repository->findByAuctionAndUser( $auction_id, $user_id );
        if ( $existing && $existing->isActive() ) {
            throw new \Exception( 'User already has active proxy bid for this auction' );
        }
        
        $now = new \DateTime();
        
        // Create proxy bid model
        $proxy_bid_data = [
            'id'                  => 0, // Will be generated by DB
            'auction_id'          => $auction_id,
            'user_id'             => $user_id,
            'maximum_bid'         => $maximum_bid,
            'current_proxy_bid'   => 0.00, // Will be set by AutoBiddingEngine when bid placed
            'status'              => ProxyBid::STATUS_ACTIVE,
            'cancelled_by_user'   => false,
            'created_at'          => $now,
            'updated_at'          => $now,
            'notes'               => $extra_data['notes'] ?? null,
        ];
        
        $proxy_bid = ProxyBid::create( $proxy_bid_data );
        
        // Save to repository
        $id = $this->repository->save( $proxy_bid );
        
        // Reload to get full object with ID
        return $this->repository->find( $id );
    }
    
    /**
     * Update proxy bid maximum
     *
     * REQ-AB-008: Ensure new maximum >= current proxy bid
     *
     * @param ProxyBid $proxy_bid    Proxy bid to update
     * @param float    $new_maximum  New maximum bid amount
     * @return ProxyBid Updated proxy bid
     * @throws \Exception If update fails validation
     */
    public function updateMaximumBid( ProxyBid $proxy_bid, float $new_maximum ): ProxyBid {
        // Validate new maximum
        if ( $new_maximum <= 0 ) {
            throw new \InvalidArgumentException( 'Maximum bid must be greater than zero' );
        }
        
        // Ensure new maximum >= current proxy bid (REQ-AB-008)
        if ( $new_maximum < $proxy_bid->getCurrentProxyBid() ) {
            throw new \Exception( 
                'New maximum bid cannot be less than current proxy bid amount' 
            );
        }
        
        // Create updated proxy bid (since immutable, must create new)
        $updated_data = $proxy_bid->toArray();
        $updated_data['maximum_bid'] = $new_maximum;
        $updated_data['updated_at'] = new \DateTime();
        
        $updated = ProxyBid::create( $updated_data );
        
        // Save update
        $this->repository->update( $updated );
        
        // Return fresh copy
        return $this->repository->find( $proxy_bid->getId() );
    }
    
    /**
     * Update current proxy bid amount
     *
     * Called by AutoBiddingEngine when placing auto-bid
     *
     * @param ProxyBid $proxy_bid      Proxy bid to update
     * @param float    $new_bid_amount New bid amount
     * @return ProxyBid Updated proxy bid
     * @throws \Exception If validation fails
     */
    public function updateCurrentBid( ProxyBid $proxy_bid, float $new_bid_amount ): ProxyBid {
        // Validate bid doesn't exceed maximum (REQ-AB-008)
        if ( $new_bid_amount > $proxy_bid->getMaximumBid() ) {
            throw new \Exception( 'Bid amount exceeds maximum bid' );
        }
        
        // Ensure bid is increasing
        if ( $new_bid_amount < $proxy_bid->getCurrentProxyBid() ) {
            throw new \Exception( 'New bid must be greater than current proxy bid' );
        }
        
        // Update current bid
        $updated_data = $proxy_bid->toArray();
        $updated_data['current_proxy_bid'] = $new_bid_amount;
        $updated_data['updated_at'] = new \DateTime();
        
        $updated = ProxyBid::create( $updated_data );
        $this->repository->update( $updated );
        
        return $this->repository->find( $proxy_bid->getId() );
    }
    
    /**
     * Mark proxy bid as outbid
     *
     * @param ProxyBid $proxy_bid Proxy bid to mark
     * @return ProxyBid Updated proxy bid
     */
    public function markOutbid( ProxyBid $proxy_bid ): ProxyBid {
        $updated_data = $proxy_bid->toArray();
        $updated_data['status'] = ProxyBid::STATUS_OUTBID;
        $updated_data['updated_at'] = new \DateTime();
        
        $updated = ProxyBid::create( $updated_data );
        $this->repository->update( $updated );
        
        return $this->repository->find( $proxy_bid->getId() );
    }
    
    /**
     * Cancel proxy bid
     *
     * @param ProxyBid $proxy_bid Proxy bid to cancel
     * @return ProxyBid Updated proxy bid
     */
    public function cancelProxyBid( ProxyBid $proxy_bid ): ProxyBid {
        $updated_data = $proxy_bid->toArray();
        $updated_data['status'] = ProxyBid::STATUS_CANCELLED;
        $updated_data['cancelled_by_user'] = true;
        $updated_data['cancelled_at'] = new \DateTime();
        $updated_data['updated_at'] = new \DateTime();
        
        $updated = ProxyBid::create( $updated_data );
        $this->repository->update( $updated );
        
        return $this->repository->find( $proxy_bid->getId() );
    }
    
    /**
     * End proxy bid (auction ended)
     *
     * @param ProxyBid $proxy_bid Proxy bid to end
     * @return ProxyBid Updated proxy bid
     */
    public function endProxyBid( ProxyBid $proxy_bid ): ProxyBid {
        $updated_data = $proxy_bid->toArray();
        $updated_data['status'] = ProxyBid::STATUS_ENDED;
        $updated_data['ended_at'] = new \DateTime();
        $updated_data['updated_at'] = new \DateTime();
        
        $updated = ProxyBid::create( $updated_data );
        $this->repository->update( $updated );
        
        return $this->repository->find( $proxy_bid->getId() );
    }
    
    /**
     * Check if proxy bid is active
     *
     * @param ProxyBid $proxy_bid Proxy bid to check
     * @return bool
     */
    public function isProxyBidActive( ProxyBid $proxy_bid ): bool {
        return $proxy_bid->isActive();
    }
    
    /**
     * Get user's active proxy bids
     *
     * @param int $user_id User ID
     * @return ProxyBid[]
     */
    public function getActiveProxyBids( int $user_id ): array {
        return $this->repository->findActiveByUser( $user_id );
    }
    
    /**
     * Get active proxy bids for an auction
     *
     * @param int $auction_id Auction ID
     * @return ProxyBid[]
     */
    public function getActiveProxyBidsForAuction( int $auction_id ): array {
        return $this->repository->findActiveByAuction( $auction_id );
    }
    
    /**
     * Get proxy bid by ID
     *
     * @param int $proxy_bid_id Proxy bid ID
     * @return ProxyBid|null
     */
    public function getProxyBid( int $proxy_bid_id ): ?ProxyBid {
        return $this->repository->find( $proxy_bid_id );
    }
    
    /**
     * Get proxy bid for user and auction
     *
     * @param int $auction_id Auction ID
     * @param int $user_id    User ID
     * @return ProxyBid|null
     */
    public function getProxyBidForAuction( int $auction_id, int $user_id ): ?ProxyBid {
        return $this->repository->findByAuctionAndUser( $auction_id, $user_id );
    }
}
